CC=gcc
CFLAGS=-g -Wall 
LDFLAGS=-lxml2 -lcap -lattr -lrpmio -lsmack
INCLUDES=-I/usr/include/libxml2 -I..

all: msmmatch

msmmatch: msmmatch.o
	 $(CC) -o $@ $^ $(LDFLAGS)

.c.o:
	$(CC) $(INCLUDES) $(CFLAGS) -c $< -o $@

clean:
	rm msmmatch *.o
